# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a22167098dd38d399b57de449d2209af30e1983e4084893c03bd986505346a85d8e8e6541e8e7d6017932af86415c0e6c5fffd3b54b1ab5c177588852b62f44

test:
  secret_key_base: 3f2b2cefdb77a3a977a563857dacb4eb7aa5c1948c66c29d33d80630f2e8a886e2932066f49dfb0c95a5ebe5376469421be5158b25b7ed35f6bb5bfe628153db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
